service: sls-crud-serverless

provider:
  name: aws
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 128
  timeout: 3

plugins:
  - serverless-offline

functions:
  list_users:
    handler: app/backend/my_functions/user_functions.list_users
    description: return list users
    runtime: python3.10
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: user/list/
          method: GET
          cors: true

  create_user:
    handler: app/backend/my_functions/user_functions.create_user
    description: inser users
    runtime: python3.10
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: user/insert/
          method: POST
          cors: true

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000  # Porta na qual o serverless-offline vai rodar dentro do contêiner