service: sls-crud-serverless

provider:
  name: aws
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 128
  timeout: 3

plugins:
  - serverless-offline

functions:
  handler:
    handler: app/backend/my_functions/user_functions.database_config
    description: function responsável por verificar as tabelas
    runtime: python3.10
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: user/config/
          method: GET
          cors: true


custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000  # Porta na qual o serverless-offline vai rodar dentro do contêiner